package org.ocpsoft.prettytime.i18n;
// Copy this to prettytime-3.2.4.Final.jar
import java.util.ListResourceBundle;

public class TWITTER_Resources extends ListResourceBundle
{
    private static final Object[][] OBJECTS = new Object[][] {
            { "CenturyPattern", "%n %u" },
            { "CenturyFuturePrefix", "" },
            { "CenturyFutureSuffix", " from now" },
            { "CenturyPastPrefix", "" },
            { "CenturyPastSuffix", "" },
            { "CenturySingularName", "century" },
            { "CenturyPluralName", "centuries" },
            { "DayPattern", "%n %u" },
            { "DayFuturePrefix", "" },
            { "DayFutureSuffix", " from now" },
            { "DayPastPrefix", "" },
            { "DayPastSuffix", "" },
            { "DaySingularName", "d" },
            { "DayPluralName", "d" },
            { "DecadePattern", "%n %u" },
            { "DecadeFuturePrefix", "" },
            { "DecadeFutureSuffix", " from now" },
            { "DecadePastPrefix", "" },
            { "DecadePastSuffix", "" },
            { "DecadeSingularName", "decade" },
            { "DecadePluralName", "decades" },
            { "HourPattern", "%n %u" },
            { "HourFuturePrefix", "" },
            { "HourFutureSuffix", " from now" },
            { "HourPastPrefix", "" },
            { "HourPastSuffix", "" },
            { "HourSingularName", "h" },
            { "HourPluralName", "h" },
            { "JustNowPattern", "%u" },
            { "JustNowFuturePrefix", "" },
            { "JustNowFutureSuffix", "moments from now" },
            { "JustNowPastPrefix", "now" },
            { "JustNowPastSuffix", "" },
            { "JustNowSingularName", "" },
            { "JustNowPluralName", "" },
            { "MillenniumPattern", "%n %u" },
            { "MillenniumFuturePrefix", "" },
            { "MillenniumFutureSuffix", " from now" },
            { "MillenniumPastPrefix", "" },
            { "MillenniumPastSuffix", "" },
            { "MillenniumSingularName", "millennium" },
            { "MillenniumPluralName", "millennia" },
            { "MillisecondPattern", "%n %u" },
            { "MillisecondFuturePrefix", "" },
            { "MillisecondFutureSuffix", " from now" },
            { "MillisecondPastPrefix", "" },
            { "MillisecondPastSuffix", "" },
            { "MillisecondSingularName", "ms" },
            { "MillisecondPluralName", "ms" },
            { "MinutePattern", "%n %u" },
            { "MinuteFuturePrefix", "" },
            { "MinuteFutureSuffix", " from now" },
            { "MinutePastPrefix", "" },
            { "MinutePastSuffix", "" },
            { "MinuteSingularName", "m" },
            { "MinutePluralName", "m" },
            { "MonthPattern", "%n %u" },
            { "MonthFuturePrefix", "" },
            { "MonthFutureSuffix", " from now" },
            { "MonthPastPrefix", "" },
            { "MonthPastSuffix", "" },
            { "MonthSingularName", "month" },
            { "MonthPluralName", "months" },
            { "SecondPattern", "%n %u" },
            { "SecondFuturePrefix", "" },
            { "SecondFutureSuffix", " from now" },
            { "SecondPastPrefix", "" },
            { "SecondPastSuffix", "" },
            { "SecondSingularName", "s" },
            { "SecondPluralName", "s" },
            { "WeekPattern", "%n %u" },
            { "WeekFuturePrefix", "" },
            { "WeekFutureSuffix", " from now" },
            { "WeekPastPrefix", "" },
            { "WeekPastSuffix", "" },
            { "WeekSingularName", "week" },
            { "WeekPluralName", "weeks" },
            { "YearPattern", "%n %u" },
            { "YearFuturePrefix", "" },
            { "YearFutureSuffix", " from now" },
            { "YearPastPrefix", "" },
            { "YearPastSuffix", "" },
            { "YearSingularName", "year" },
            { "YearPluralName", "years" },
            { "AbstractTimeUnitPattern", "" },
            { "AbstractTimeUnitFuturePrefix", "" },
            { "AbstractTimeUnitFutureSuffix", "" },
            { "AbstractTimeUnitPastPrefix", "" },
            { "AbstractTimeUnitPastSuffix", "" },
            { "AbstractTimeUnitSingularName", "" },
            { "AbstractTimeUnitPluralName", "" } };

    @Override
    protected Object[][] getContents()
    {
        return OBJECTS;
    }
}